config/routes.rb
ShoutyApp::Application.routes.draw do
  resources :shouties do
    collection do
      get :fetch
    end
  end
  root :to => 'shouties#index'
  devise_for :users
end

app/models/shouty.rb
class Shouty < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user, :body
  default_scope order('id DESC')
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :login
  validates_uniqueness_of :login

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :login
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/shouties_controller.rb
class ShoutiesController < InheritedResources::Base
  before_filter :authenticate_user!
  before_filter :assign_user, :only => [:create]

  respond_to :html, :js
  
  def index
    @shouty = Shouty.new
    index!
  end
  
  def fetch
    collection
  end
  
  protected
  
  def collection
    @shouties ||= end_of_association_chain.paginate(:page => params[:page])
  end
  
  private
  
  def assign_user
    params[:shouty][:user] = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def message(name)
    "<div class='#{name}'>#{eval(name.to_s)}</div>" if eval(name.to_s)
  end
end

app/views/layouts/application.html.haml
!!! XML
!!!
%html
  %head
    %title Shouty
    = stylesheet_link_tag 'screen', :media => 'screen, projection'
    = stylesheet_link_tag 'print', :media => 'print'
    /[if lt IE 8]
      = stylesheet_link_tag 'ie', :media => 'screen, projection'
    = csrf_meta_tag
  %body
    #container
      #header
        %h1 Shouty
        - if user_signed_in?
          .logout= link_to t(:logout), destroy_user_session_path 
      #content
        #flash= %w(notice alert).map { |key| message(key) }.join.html_safe
        = yield
      #footer
    %script{ :type => "text/javascript", :src => "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" }
    %script{ :type => "text/javascript", :src => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js" }
    = javascript_include_tag :all

app/views/shared/_shouty.haml
.shouty{ :id => "shouty_#{shouty.id}" }
  .avatar= gravatar_for(shouty.user).html_safe
  .body= auto_link(shouty.body, :html => { :target => "_blank" }) { |text| truncate(text, :length => 15) }
  .user= shouty.user.login
  .date= "#{time_ago_in_words(shouty.created_at)} #{I18n.t(:ago)}"
  - if shouty.user == current_user
    = link_to t(:delete), shouty, :remote => true, :method => :delete

app/views/shouties/create.js.erb
afterShoutyCreated("<%= escape_javascript(render("shared/shouty", :shouty => @shouty)) %>");

app/views/shouties/destroy.js.erb
removeShouty(<%= @shouty.id %>);

app/views/shouties/fetch.js.erb
updateShoutiesFrom("<%= escape_javascript(render(:partial => "shared/shouty", :collection => @shouties)) %>");

app/views/shouties/index.html.haml
= semantic_form_for @shouty, :remote => true do |form|
  = form.inputs do
    = form.input :body, :label => false
  = form.buttons do
    = form.commit_button :label => "shoutt!"

.shouties= render :partial => "shared/shouty", :collection => @shouties

= link_to t(:update), fetch_shouties_path, :remote => true, :id => "update_shouties"